#!/bin/bash
# LP Long Horizon Read-only Collector - 6h staged run launcher
# Stage: 6h
# Run ID: 20260604_130353
# Generated by LP_LONG_HORIZON_READONLY_COLLECTOR_6H_RUN_APPROVAL_V1
# Approval: APPROVE_LP_LONG_HORIZON_READONLY_STAGE_RUN stage=6h mode=readonly no_probe=true
# This launcher is invoked once to start the tmux session.
# It MUST be run after MANUAL_APPROVAL_RECORDED.json exists and PRE_RUN_SAFETY_CHECK passes.

set -euo pipefail

RUN_ID="20260604_130353"
SESSION="lp_long_horizon_6h_${RUN_ID}"
LOG_DIR="reports/lp_long_horizon_readonly_collector_6h_run/${RUN_ID}/logs"
DATA_DIR="data/lp_long_horizon/${RUN_ID}"
APPROVAL_RECORD="reports/lp_long_horizon_readonly_collector_6h_run/${RUN_ID}/MANUAL_APPROVAL_RECORDED.json"

# preflight: verify approval record exists and phrase matches
if [[ ! -f "${APPROVAL_RECORD}" ]]; then
    echo "REFUSED: APPROVAL_RECORD.json not found at ${APPROVAL_RECORD}" >&2
    exit 11
fi
APPROVAL_PHRASE=$(python3 -c "import json; print(json.load(open('${APPROVAL_RECORD}'))['user_approval_text'])")
EXPECTED="APPROVE_LP_LONG_HORIZON_READONLY_STAGE_RUN stage=6h mode=readonly no_probe=true"
if [[ "${APPROVAL_PHRASE}" != "${EXPECTED}" ]]; then
    echo "REFUSED: approval phrase mismatch" >&2
    echo "  got:      ${APPROVAL_PHRASE}" >&2
    echo "  expected: ${EXPECTED}" >&2
    exit 12
fi

# preflight: no existing tmux session with same name
if tmux has-session -t "${SESSION}" 2>/dev/null; then
    echo "REFUSED: tmux session ${SESSION} already exists" >&2
    exit 13
fi

# create dirs
mkdir -p "${LOG_DIR}" "${DATA_DIR}"

# 6h loop: 6 iterations, 1h sleep between (per six_hour_run_config.json)
# Each iteration runs collector --mode smoke which produces 1 pass data.
# We run the FIRST iteration synchronously and detach the rest to the tmux session.

LOOP_CMD=$(cat <<'BASH_EOF'
cd /opt/lpbot/lp-bot-v3-origin-check
RUN_ID=20260604_130353
DATA_DIR=data/lp_long_horizon/${RUN_ID}
LOG_DIR=reports/lp_long_horizon_readonly_collector_6h_run/${RUN_ID}/logs
START_TS=$(date -u +%Y-%m-%dT%H:%M:%SZ)
echo "[6h start] ${START_TS}" | tee -a "${LOG_DIR}/run.log"

# heartbeat every 15 min for 6h (4 per hour * 6 = 24 heartbeats)
heartbeat() {
    local i=$1
    echo "[heartbeat ${i}] $(date -u +%Y-%m-%dT%H:%M:%SZ) pid=$$ session=lp_long_horizon_6h_${RUN_ID}" | tee -a "${LOG_DIR}/run.log"
}

# initial heartbeat
heartbeat 0
for i in 1 2 3 4 5 6; do
    CKPT_DIR="${DATA_DIR}/checkpoint_${i}_$(date -u +%H%M)"
    mkdir -p "${CKPT_DIR}"
    echo "[checkpoint ${i}/6] start at $(date -u +%Y-%m-%dT%H:%M:%SZ) -> ${CKPT_DIR}" | tee -a "${LOG_DIR}/run.log"
    if python3 scripts/lp_long_horizon_readonly_collector_v1.py \
        --mode smoke \
        --pools-per-protocol 5 \
        --out "${CKPT_DIR}" \
        --no-wallet --no-tx --no-bridge --dry-run 2>&1 | tee -a "${LOG_DIR}/run.log"; then
        echo "[checkpoint ${i}/6] ok at $(date -u +%Y-%m-%dT%H:%M:%SZ)" | tee -a "${LOG_DIR}/run.log"
    else
        echo "[checkpoint ${i}/6] FAILED at $(date -u +%Y-%m-%dT%H:%M:%SZ), aborting 6h run" | tee -a "${LOG_DIR}/run.log"
        echo "[6h abort] ckpt=${i} run_id=${RUN_ID} at $(date -u +%Y-%m-%dT%H:%M:%SZ)" | tee -a "${LOG_DIR}/run.log"
        exit 1
    fi
    if [ "$i" -lt 6 ]; then
        # 1h sleep with periodic heartbeat
        for q in 1 2 3 4; do
            sleep 900  # 15 min
            heartbeat "${i}_${q}_of_4"
        done
    fi
done
END_TS=$(date -u +%Y-%m-%dT%H:%M:%SZ)
echo "[6h end] ${END_TS}" | tee -a "${LOG_DIR}/run.log"
echo "[6h finalize] start at $(date -u +%Y-%m-%dT%H:%M:%SZ)" | tee -a "${LOG_DIR}/run.log"

# Finalize: write aggregate summary marker
python3 <<'PY_EOF'
import json
from pathlib import Path
from datetime import datetime, timezone
RUN_ID = "20260604_130353"
DATA_DIR = Path(f"data/lp_long_horizon/{RUN_ID}")
LOG_DIR = Path(f"reports/lp_long_horizon_readonly_collector_6h_run/{RUN_ID}/logs")
ckpt_dirs = sorted([p for p in DATA_DIR.iterdir() if p.is_dir() and p.name.startswith("checkpoint_")])
total_pool = total_quote = total_fee = total_liq = total_regime = 0
for d in ckpt_dirs:
    for f, key in [
        ("pool_snapshots.jsonl", "pool"),
        ("quote_snapshots.jsonl", "quote"),
        ("fee_velocity.jsonl", "fee"),
        ("liquidity_distribution.jsonl", "liq"),
    ]:
        p = d / f
        if p.exists():
            with p.open() as fh:
                total_pool += int(key == "pool")
                for line in fh:
                    if line.strip():
                        if key == "pool": total_pool += 1
                        elif key == "quote": total_quote += 1
                        elif key == "fee": total_fee += 1
                        elif key == "liq": total_liq += 1
    p = d / "market_regime.jsonl"
    if p.exists():
        with p.open() as fh:
            for line in fh:
                if line.strip():
                    total_regime += 1
summary = {
    "stage": "6h",
    "run_id": RUN_ID,
    "completed_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    "checkpoint_count": len(ckpt_dirs),
    "checkpoint_dirs": [str(d) for d in ckpt_dirs],
    "row_counts": {
        "pool_snapshots": total_pool,
        "quote_snapshots": total_quote,
        "fee_velocity": total_fee,
        "liquidity_distribution": total_liq,
        "market_regime": total_regime,
    },
    "wallet_or_tx_touched": False,
    "transaction_sent": False,
    "auto_advance_to_12h": False,
    "next_action": "await manual approval for 12h",
}
with (LOG_DIR / "aggregate_summary.json").open("w") as fh:
    json.dump(summary, fh, indent=2, ensure_ascii=False)
print(f"[6h aggregate] ckpts={len(ckpt_dirs)} pool={total_pool} quote={total_quote} fee={total_fee} liq={total_liq} regime={total_regime}")
PY_EOF

echo "[6h finalize] done at $(date -u +%Y-%m-%dT%H:%M:%SZ)" | tee -a "${LOG_DIR}/run.log"
echo "[6h run ready for finalize stage] please run: bash reports/lp_long_horizon_readonly_collector_6h_run/${RUN_ID}/finalize_6h_run.sh" | tee -a "${LOG_DIR}/run.log"
BASH_EOF
)

# launch tmux session (1 hour initial sleep shortened to 30s for smoke test, real 6h run uses 3600s)
# for the real 6h run, the inner sleep 900 x 4 = 3600s (1h)
# for smoke test we use a shorter version

# Use a separate file for the loop body (cleaner tmux attach)
cat > "${LOG_DIR}/loop_body.sh" <<'BASH_EOF'
#!/bin/bash
set -euo pipefail
cd /opt/lpbot/lp-bot-v3-origin-check
RUN_ID=20260604_130353
DATA_DIR="data/lp_long_horizon/${RUN_ID}"
LOG_DIR="reports/lp_long_horizon_readonly_collector_6h_run/${RUN_ID}/logs"
START_TS=$(date -u +%Y-%m-%dT%H:%M:%SZ)
echo "[6h start] ${START_TS}" | tee -a "${LOG_DIR}/run.log"

# Special mode: SHORT loop for smoke (loop_count=2, sleep=30s between)
# Real 6h uses loop_count=6, sleep=3600s; smoke uses 2/30s to verify pipeline
LOOP_COUNT="${LOOP_COUNT:-6}"
SLEEP_SECONDS="${SLEEP_SECONDS:-3600}"

heartbeat() {
    local i=$1
    echo "[heartbeat ${i}] $(date -u +%Y-%m-%dT%H:%M:%SZ) pid=$$ session=lp_long_horizon_6h_${RUN_ID}" | tee -a "${LOG_DIR}/run.log"
}

heartbeat 0
for i in $(seq 1 $LOOP_COUNT); do
    CKPT_DIR="${DATA_DIR}/checkpoint_${i}_$(date -u +%H%M)"
    mkdir -p "${CKPT_DIR}"
    echo "[checkpoint ${i}/${LOOP_COUNT}] start at $(date -u +%Y-%m-%dT%H:%M:%SZ) -> ${CKPT_DIR}" | tee -a "${LOG_DIR}/run.log"
    if python3 scripts/lp_long_horizon_readonly_collector_v1.py \
        --mode smoke \
        --pools-per-protocol 5 \
        --out "${CKPT_DIR}" \
        --no-wallet --no-tx --no-bridge --dry-run 2>&1 | tee -a "${LOG_DIR}/run.log"; then
        echo "[checkpoint ${i}/${LOOP_COUNT}] ok at $(date -u +%Y-%m-%dT%H:%M:%SZ)" | tee -a "${LOG_DIR}/run.log"
    else
        echo "[checkpoint ${i}/${LOOP_COUNT}] FAILED at $(date -u +%Y-%m-%dT%H:%M:%SZ), aborting 6h run" | tee -a "${LOG_DIR}/run.log"
        exit 1
    fi
    if [ "$i" -lt $LOOP_COUNT ]; then
        for q in 1 2 3 4; do
            sleep $((SLEEP_SECONDS / 4))
            heartbeat "${i}_${q}_of_4"
        done
    fi
done
END_TS=$(date -u +%Y-%m-%dT%H:%M:%SZ)
echo "[6h end] ${END_TS}" | tee -a "${LOG_DIR}/run.log"
BASH_EOF
chmod +x "${LOG_DIR}/loop_body.sh"

# tmux new-session detached
tmux new-session -d -s "${SESSION}" -c "$(pwd)" "LOOP_COUNT=6 SLEEP_SECONDS=3600 bash ${LOG_DIR}/loop_body.sh 2>&1 | tee -a ${LOG_DIR}/run.log"

if ! tmux has-session -t "${SESSION}" 2>/dev/null; then
    echo "REFUSED: tmux session ${SESSION} failed to start" >&2
    exit 14
fi
echo "[ok] tmux session started: ${SESSION}"
echo "[info] attach: tmux attach -t ${SESSION}"
echo "[info] kill when done: tmux kill-session -t ${SESSION}"
echo "[info] log: tail -f ${LOG_DIR}/run.log"
