// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type DryrunPool struct {
	PoolID       string         `json:"pool_id"`
	Chain        int64          `json:"chain"`
	Protocol     string         `json:"protocol"`
	Token0       string         `json:"token0"`
	Token1       string         `json:"token1"`
	FeeBps       int64          `json:"fee_bps"`
	Tier         sql.NullString `json:"tier"`
	AuditVerdict sql.NullString `json:"audit_verdict"`
	LastScore    sql.NullString `json:"last_score"`
	UpdatedBlock int64          `json:"updated_block"`
	UpdatedAt    int64          `json:"updated_at"`
}

type DryrunPoolScoreHistory struct {
	ID          int64  `json:"id"`
	PoolID      string `json:"pool_id"`
	Chain       int64  `json:"chain"`
	BlockNumber int64  `json:"block_number"`
	BlockHash   string `json:"block_hash"`
	BlockTime   int64  `json:"block_time"`
	ScoreJson   string `json:"score_json"`
	TraceID     string `json:"trace_id"`
}
