// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pools.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getPool = `-- name: GetPool :one
SELECT
    pool_id, chain, protocol, token0, token1, fee_bps,
    tier, last_score, updated_block, updated_at
FROM dryrun_pools
WHERE pool_id = ?1
`

type GetPoolRow struct {
	PoolID       string         `json:"pool_id"`
	Chain        int64          `json:"chain"`
	Protocol     string         `json:"protocol"`
	Token0       string         `json:"token0"`
	Token1       string         `json:"token1"`
	FeeBps       int64          `json:"fee_bps"`
	Tier         sql.NullString `json:"tier"`
	LastScore    sql.NullString `json:"last_score"`
	UpdatedBlock int64          `json:"updated_block"`
	UpdatedAt    int64          `json:"updated_at"`
}

// Retrieves a single pool by its ID.
// Returns the pool row or no_rows error.
func (q *Queries) GetPool(ctx context.Context, poolID string) (GetPoolRow, error) {
	row := q.db.QueryRowContext(ctx, getPool, poolID)
	var i GetPoolRow
	err := row.Scan(
		&i.PoolID,
		&i.Chain,
		&i.Protocol,
		&i.Token0,
		&i.Token1,
		&i.FeeBps,
		&i.Tier,
		&i.LastScore,
		&i.UpdatedBlock,
		&i.UpdatedAt,
	)
	return i, err
}

const getPoolScoreHistory = `-- name: GetPoolScoreHistory :many
SELECT
    id, pool_id, chain, block_number, block_hash, block_time,
    score_json, trace_id
FROM dryrun_pool_score_history
WHERE pool_id = ?1
ORDER BY block_number DESC
LIMIT ?2
`

type GetPoolScoreHistoryParams struct {
	PoolID string `json:"pool_id"`
	Limit  int64  `json:"limit"`
}

// Returns score history for a pool, ordered by block_number DESC.
// If limit <= 0, returns all available history.
func (q *Queries) GetPoolScoreHistory(ctx context.Context, arg GetPoolScoreHistoryParams) ([]DryrunPoolScoreHistory, error) {
	rows, err := q.db.QueryContext(ctx, getPoolScoreHistory, arg.PoolID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DryrunPoolScoreHistory
	for rows.Next() {
		var i DryrunPoolScoreHistory
		if err := rows.Scan(
			&i.ID,
			&i.PoolID,
			&i.Chain,
			&i.BlockNumber,
			&i.BlockHash,
			&i.BlockTime,
			&i.ScoreJson,
			&i.TraceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPoolScoreHistory = `-- name: InsertPoolScoreHistory :exec
INSERT INTO dryrun_pool_score_history (
    pool_id, chain, block_number, block_hash, block_time, score_json, trace_id
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7
)
`

type InsertPoolScoreHistoryParams struct {
	PoolID      string `json:"pool_id"`
	Chain       int64  `json:"chain"`
	BlockNumber int64  `json:"block_number"`
	BlockHash   string `json:"block_hash"`
	BlockTime   int64  `json:"block_time"`
	ScoreJson   string `json:"score_json"`
	TraceID     string `json:"trace_id"`
}

// Appends a score snapshot to the pool's score history.
func (q *Queries) InsertPoolScoreHistory(ctx context.Context, arg InsertPoolScoreHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertPoolScoreHistory,
		arg.PoolID,
		arg.Chain,
		arg.BlockNumber,
		arg.BlockHash,
		arg.BlockTime,
		arg.ScoreJson,
		arg.TraceID,
	)
	return err
}

const listPools = `-- name: ListPools :many
SELECT
    pool_id, chain, protocol, token0, token1, fee_bps,
    tier, last_score, updated_block, updated_at
FROM dryrun_pools
WHERE
    (?1 IS NULL OR chain = ?1)
ORDER BY updated_at DESC
LIMIT ?2
`

type ListPoolsParams struct {
	Chain interface{} `json:"chain"`
	Limit int64       `json:"limit"`
}

type ListPoolsRow struct {
	PoolID       string         `json:"pool_id"`
	Chain        int64          `json:"chain"`
	Protocol     string         `json:"protocol"`
	Token0       string         `json:"token0"`
	Token1       string         `json:"token1"`
	FeeBps       int64          `json:"fee_bps"`
	Tier         sql.NullString `json:"tier"`
	LastScore    sql.NullString `json:"last_score"`
	UpdatedBlock int64          `json:"updated_block"`
	UpdatedAt    int64          `json:"updated_at"`
}

// Returns pools filtered by chain, ordered by updated_at DESC.
// If limit <= 0, uses default limit of 100.
func (q *Queries) ListPools(ctx context.Context, arg ListPoolsParams) ([]ListPoolsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPools, arg.Chain, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPoolsRow
	for rows.Next() {
		var i ListPoolsRow
		if err := rows.Scan(
			&i.PoolID,
			&i.Chain,
			&i.Protocol,
			&i.Token0,
			&i.Token1,
			&i.FeeBps,
			&i.Tier,
			&i.LastScore,
			&i.UpdatedBlock,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAuditVerdict = `-- name: UpsertAuditVerdict :exec
UPDATE dryrun_pools
SET
    tier = ?1,
    audit_verdict = ?2,
    updated_at = ?3
WHERE pool_id = ?4
`

type UpsertAuditVerdictParams struct {
	Tier         sql.NullString `json:"tier"`
	AuditVerdict sql.NullString `json:"audit_verdict"`
	UpdatedAt    int64          `json:"updated_at"`
	PoolID       string         `json:"pool_id"`
}

// Updates the audit verdict for a pool.
func (q *Queries) UpsertAuditVerdict(ctx context.Context, arg UpsertAuditVerdictParams) error {
	_, err := q.db.ExecContext(ctx, upsertAuditVerdict,
		arg.Tier,
		arg.AuditVerdict,
		arg.UpdatedAt,
		arg.PoolID,
	)
	return err
}

const upsertPool = `-- name: UpsertPool :exec
INSERT INTO dryrun_pools (
    pool_id, chain, protocol, token0, token1, fee_bps,
    tier, last_score, updated_block, updated_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6,
    ?7, ?8, ?9, ?10
)
ON CONFLICT(pool_id) DO UPDATE SET
    protocol = excluded.protocol,
    token0 = excluded.token0,
    token1 = excluded.token1,
    fee_bps = excluded.fee_bps,
    tier = excluded.tier,
    last_score = excluded.last_score,
    updated_block = excluded.updated_block,
    updated_at = excluded.updated_at
`

type UpsertPoolParams struct {
	PoolID       string         `json:"pool_id"`
	Chain        int64          `json:"chain"`
	Protocol     string         `json:"protocol"`
	Token0       string         `json:"token0"`
	Token1       string         `json:"token1"`
	FeeBps       int64          `json:"fee_bps"`
	Tier         sql.NullString `json:"tier"`
	LastScore    sql.NullString `json:"last_score"`
	UpdatedBlock int64          `json:"updated_block"`
	UpdatedAt    int64          `json:"updated_at"`
}

// Upserts pool metadata with score snapshot.
// Writes to dryrun_pools table and appends to dryrun_pool_score_history.
func (q *Queries) UpsertPool(ctx context.Context, arg UpsertPoolParams) error {
	_, err := q.db.ExecContext(ctx, upsertPool,
		arg.PoolID,
		arg.Chain,
		arg.Protocol,
		arg.Token0,
		arg.Token1,
		arg.FeeBps,
		arg.Tier,
		arg.LastScore,
		arg.UpdatedBlock,
		arg.UpdatedAt,
	)
	return err
}
