#!/usr/bin/env python3
"""Zero-RPC Stage-1 proxy and honest proxy/NetCover correlation contracts.

The proxy consumes only fields already returned by the free DefiLlama pool
feed (plus ``fee_tier`` parsed locally from its ``poolMeta`` string).  It is a
lead-ranking model, never an entry gate.  Terminal NetCover remains the sole
economic gate and missing proxy evidence fails closed to the APR fallback.

The M1 position is fixed at 50 USD.  Position size is deliberately not an
optimisation/ranking feature: audit evidence shows fee tier and holding horizon,
not larger capital, dominate the fixed round-trip drag.
"""
from __future__ import annotations

import math
import sys
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

_REPO_ROOT = Path(__file__).resolve().parents[1]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from scripts.lp_netcover_engine_v1_readonly import REWARD_HAIRCUTS
from scripts.lp_netcover_inputs_v1_readonly import (
    HISTORICAL_GAS_USD,
    LVR_COEFFICIENT_MODEL,
    reward_category,
)
from scripts.lp_portfolio_allocator_v1_readonly import M1_MIN_POSITION_USD
from scripts.lp_universe_screener_v1_readonly import MAJOR_STABLES, MAJOR_TOKENS, split_symbol_legs


HOURS_PER_YEAR = 8_760.0
DEFAULT_PROXY_HORIZON_HOURS = 30.0 * 24.0
PROXY_VALID_SPEARMAN_MIN = 0.30
MIN_CORRELATION_PAIRS = 8
EMISSION_DOMINANT_SHARE_MIN = 0.50
NON_BLUECHIP_REWARD_RELIABILITY = 0.50
UNKNOWN_OR_EXOTIC_IL_MULTIPLIER = 1.25
LOW_IL_FLAG_MULTIPLIER = 0.50

# Audited same-batch evidence generated by the research-only evaluator after
# ADD-1. Target-expansion rows were excluded from correlation, so no target
# identity participates in production ranking. ``rank_stage1`` independently
# rechecks all three fields instead of trusting the boolean alone.
PRODUCTION_EVIDENCE = {
    "artifact": "reports/lp_funnel_rerank/20260809_135500/correlation.json",
    "artifact_sha256": "050f8b44487a5cf58afb1f42ce550d28e02ec1970aef7dc2d85a855390d2bb8b",
    "spearman": 0.47352941176470587,
    "fully_calculable_pairs": 16,
    "proxy_valid": True,
    "correlation_cohort": "PROXY_TOP_N_ONLY",
}

_ETH_ANCHORS = frozenset({"ETH", "WETH", "CBETH", "WSTETH", "WEETH", "RETH", "EZETH", "MSETH", "WRSETH", "SUPEROETHB"})
_BTC_ANCHORS = frozenset({"BTC", "WBTC", "CBBTC", "TBTC", "LBTC"})
_USD_ANCHORS = frozenset(MAJOR_STABLES)


def _finite_nonnegative(value: Any) -> float | None:
    if value is None or isinstance(value, bool):
        return None
    try:
        parsed = float(value)
    except (TypeError, ValueError):
        return None
    return parsed if math.isfinite(parsed) and parsed >= 0.0 else None


def _same_anchor(legs: Sequence[str]) -> bool:
    if len(legs) != 2:
        return False
    return any(all(leg in group for leg in legs) for group in (_USD_ANCHORS, _ETH_ANCHORS, _BTC_ANCHORS))


def _base_result(record: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "proxy_status": "UNAVAILABLE_FAIL_CLOSED",
        "proxy_reason": None,
        "proxy_netcover": None,
        "proxy_income_apr_pct": None,
        "proxy_fee_income_apr_pct": None,
        "proxy_reward_income_apr_pct": None,
        "proxy_reward_haircut": None,
        "proxy_reward_pair_reliability": None,
        "proxy_il_apr_pct": None,
        "proxy_lvr_apr_pct": None,
        "proxy_fixed_drag_apr_pct": None,
        "proxy_cost_apr_pct": None,
        "proxy_position_usd": float(M1_MIN_POSITION_USD),
        "proxy_position_source": "M1_MIN_POSITION_USD_FIXED_NOT_RANKING_FACTOR",
        "proxy_horizon_hours": DEFAULT_PROXY_HORIZON_HOURS,
        "proxy_horizon_source": "fixed_30d_stage1_comparison_not_terminal_H_selection",
        "proxy_stable_or_same_anchor": False,
        "proxy_both_legs_major": False,
        "proxy_emission_dominant_bluechip": False,
        "proxy_input_source": "DefiLlama_free_stage1_zero_rpc",
        "proxy_model_semantics": "lead_model_only_not_entry_gate",
        "original_apr_score": _finite_nonnegative(record.get("score")),
    }


def _unavailable(result: dict[str, Any], reason: str) -> dict[str, Any]:
    result["proxy_reason"] = reason
    return result


def proxy_netcover(
    record: Mapping[str, Any], *, horizon_hours: float = DEFAULT_PROXY_HORIZON_HOURS
) -> dict[str, Any]:
    """Return the terminal-shaped, free-field NetCover proxy for one pool.

    DefiLlama's generic ``sigma`` is only *assumed* to proxy daily percentage
    price volatility here; it is not the terminal gate's measured pair-price
    sigma.  The IL proxy is
    the small-return variance approximation ``0.5 * sigma_daily^2 * 365`` in
    annual percentage points.  Stable/same-anchor pairs set that component to
    zero; the fixed fee/gas drag remains.  ``ilRisk`` and major-pair identity
    change the IL risk multiplier, never add post-hoc score points.
    """
    result = _base_result(record)
    horizon = _finite_nonnegative(horizon_hours)
    if horizon is None or horizon <= 0.0:
        return _unavailable(result, "horizon_invalid")
    result["proxy_horizon_hours"] = horizon

    base = _finite_nonnegative(record.get("apyBase"))
    if base is None:
        return _unavailable(result, "apy_base_unavailable")
    raw_reward = record.get("apyReward")
    reward = 0.0 if raw_reward is None else _finite_nonnegative(raw_reward)
    if reward is None:
        return _unavailable(result, "apy_reward_invalid")
    sigma = _finite_nonnegative(record.get("sigma"))
    if sigma is None:
        return _unavailable(result, "sigma_unavailable")
    fee_tier = _finite_nonnegative(record.get("fee_tier"))
    if fee_tier is None or fee_tier <= 0.0 or fee_tier >= 1.0:
        return _unavailable(result, "fee_tier_unavailable")

    category = reward_category(record) if reward > 0.0 else None
    if reward > 0.0 and category is None:
        return _unavailable(result, "reward_category_unavailable")
    reward_haircut = REWARD_HAIRCUTS.get(category) if category else 0.0
    if reward > 0.0 and reward_haircut is None:
        return _unavailable(result, "reward_haircut_unavailable")

    legs = split_symbol_legs(record.get("symbol"))
    both_major = len(legs) == 2 and all(leg in MAJOR_TOKENS for leg in legs)
    stable_or_anchor = bool(record.get("stablecoin") is True or _same_anchor(legs))
    total_raw_income = base + reward
    reward_share = reward / total_raw_income if total_raw_income > 0.0 else 0.0
    emission_bluechip = both_major and reward_share >= EMISSION_DOMINANT_SHARE_MIN

    fee_income = base * 0.65
    # Existing category haircuts remain the primary reward reliability model.
    # ADD-2's third structural factor is conservative: only a reward-dominant
    # double-major pair retains that full haircut. Other known rewards receive
    # an additional reliability discount; target-list membership is never read.
    reward_pair_reliability = (
        1.0 if reward == 0.0 or emission_bluechip else NON_BLUECHIP_REWARD_RELIABILITY
    )
    reward_income = reward * float(reward_haircut) * reward_pair_reliability
    income = fee_income + reward_income

    if stable_or_anchor:
        il_apr = 0.0
        il_multiplier = 0.0
    else:
        il_risk = str(record.get("ilRisk") or "").strip().lower()
        if il_risk in {"no", "false", "0"}:
            il_multiplier = LOW_IL_FLAG_MULTIPLIER
        elif both_major:
            il_multiplier = 1.0
        else:
            il_multiplier = UNKNOWN_OR_EXOTIC_IL_MULTIPLIER
        # sigma is percentage/day. Convert daily variance to annual IL %.
        il_apr = 0.5 * (sigma / 100.0) ** 2 * 365.0 * 100.0 * il_multiplier
    lvr_apr = il_apr * LVR_COEFFICIENT_MODEL

    position = float(M1_MIN_POSITION_USD)
    gas = float(HISTORICAL_GAS_USD["base"])
    fixed_drag = ((2.0 * fee_tier * position + gas) / position) * (
        HOURS_PER_YEAR / horizon
    ) * 100.0
    cost = il_apr + lvr_apr + fixed_drag
    if not math.isfinite(cost) or cost <= 0.0:
        return _unavailable(result, "proxy_cost_non_positive")

    result.update({
        "proxy_status": "CALCULABLE",
        "proxy_reason": None,
        "proxy_netcover": income / cost,
        "proxy_income_apr_pct": income,
        "proxy_fee_income_apr_pct": fee_income,
        "proxy_reward_income_apr_pct": reward_income,
        "proxy_reward_haircut": float(reward_haircut),
        "proxy_reward_pair_reliability": reward_pair_reliability,
        "proxy_reward_category": category,
        "proxy_il_apr_pct": il_apr,
        "proxy_il_multiplier": il_multiplier,
        "proxy_lvr_apr_pct": lvr_apr,
        "proxy_lvr_coefficient": LVR_COEFFICIENT_MODEL,
        "proxy_fixed_drag_apr_pct": fixed_drag,
        "proxy_cost_apr_pct": cost,
        "proxy_fee_tier": fee_tier,
        "proxy_stable_or_same_anchor": stable_or_anchor,
        "proxy_both_legs_major": both_major,
        "proxy_emission_dominant_bluechip": emission_bluechip,
        "proxy_reward_share": reward_share,
    })
    return result


def enrich_with_proxy(records: Iterable[Mapping[str, Any]]) -> list[dict[str, Any]]:
    return [dict(record, **proxy_netcover(record)) for record in records]


def _average_ranks(values: Sequence[float]) -> list[float]:
    order = sorted(range(len(values)), key=lambda index: values[index])
    ranks = [0.0] * len(values)
    cursor = 0
    while cursor < len(order):
        end = cursor + 1
        while end < len(order) and values[order[end]] == values[order[cursor]]:
            end += 1
        average = ((cursor + 1) + end) / 2.0
        for position in range(cursor, end):
            ranks[order[position]] = average
        cursor = end
    return ranks


def _pearson(left: Sequence[float], right: Sequence[float]) -> float | None:
    if len(left) < 2 or len(left) != len(right):
        return None
    mean_left = sum(left) / len(left)
    mean_right = sum(right) / len(right)
    numerator = sum((x - mean_left) * (y - mean_right) for x, y in zip(left, right))
    denominator = math.sqrt(
        sum((x - mean_left) ** 2 for x in left)
        * sum((y - mean_right) ** 2 for y in right)
    )
    return numerator / denominator if denominator > 0.0 else None


def correlate_proxy_with_netcover(
    records: Sequence[Mapping[str, Any]], *, id_key: str = "llama_pool_id", top_k: int = 10
) -> dict[str, Any]:
    """Compare descending proxy/true ranks on one batch's calculable overlap."""
    if top_k <= 0:
        raise ValueError("top_k must be positive")
    pairs: list[tuple[str, float, float]] = []
    for index, record in enumerate(records):
        proxy = _finite_nonnegative(record.get("proxy_netcover"))
        actual = _finite_nonnegative(record.get("netcover_ratio"))
        if proxy is None or actual is None:
            continue
        identity = str(record.get(id_key) or record.get("pool") or index)
        pairs.append((identity, proxy, actual))
    proxy_values = [pair[1] for pair in pairs]
    actual_values = [pair[2] for pair in pairs]
    spearman = _pearson(_average_ranks(proxy_values), _average_ranks(actual_values))
    denominator = min(top_k, len(pairs))
    proxy_top = {pair[0] for pair in sorted(pairs, key=lambda pair: pair[1], reverse=True)[:denominator]}
    actual_top = {pair[0] for pair in sorted(pairs, key=lambda pair: pair[2], reverse=True)[:denominator]}
    hits = len(proxy_top & actual_top)
    valid = (
        len(pairs) >= MIN_CORRELATION_PAIRS
        and spearman is not None
        and spearman >= PROXY_VALID_SPEARMAN_MIN
    )
    return {
        "same_batch_records": len(records),
        "fully_calculable_pairs": len(pairs),
        "excluded_missing_proxy_or_true_netcover": len(records) - len(pairs),
        "spearman": spearman,
        "validity_threshold": PROXY_VALID_SPEARMAN_MIN,
        "minimum_correlation_pairs": MIN_CORRELATION_PAIRS,
        "proxy_valid": valid,
        "production_ranking": "PROXY_NETCOVER" if valid else "ORIGINAL_APR_FALLBACK",
        "top_k_requested": top_k,
        "top_k_denominator": denominator,
        "top_k_hits": hits,
        "top_k_hit_rate": hits / denominator if denominator else None,
        "top_k_definition": (
            "intersection(proxy descending top-K, true NetCover descending top-K) / "
            "min(K, fully calculable same-batch pairs)"
        ),
    }


def rank_stage1(
    records: Sequence[Mapping[str, Any]], *, correlation_evidence: Mapping[str, Any] | None
) -> list[dict[str, Any]]:
    """Rank by proxy only after valid evidence; otherwise retain APR ordering."""
    enriched = [dict(record) for record in records]
    apr_order = sorted(
        range(len(enriched)),
        key=lambda index: (
            bool(enriched[index].get("suspect")),
            -float(_finite_nonnegative(enriched[index].get("score")) or 0.0),
        ),
    )
    for rank, index in enumerate(apr_order, 1):
        enriched[index]["original_apr_rank"] = rank

    proxy_order = sorted(
        range(len(enriched)),
        key=lambda index: (
            enriched[index].get("proxy_netcover") is None,
            -float(_finite_nonnegative(enriched[index].get("proxy_netcover")) or 0.0),
            enriched[index]["original_apr_rank"],
        ),
    )
    for rank, index in enumerate(proxy_order, 1):
        enriched[index]["proxy_rank"] = rank

    evidence_spearman = (
        _finite_nonnegative(correlation_evidence.get("spearman"))
        if correlation_evidence else None
    )
    evidence_pairs = (
        int(correlation_evidence.get("fully_calculable_pairs") or 0)
        if correlation_evidence else 0
    )
    use_proxy = bool(
        correlation_evidence
        and correlation_evidence.get("proxy_valid") is True
        and evidence_spearman is not None
        and evidence_spearman >= PROXY_VALID_SPEARMAN_MIN
        and evidence_pairs >= MIN_CORRELATION_PAIRS
    )
    selected_order = proxy_order if use_proxy else apr_order
    method = "PROXY_NETCOVER" if use_proxy else "ORIGINAL_APR_FALLBACK"
    selected = [enriched[index] for index in selected_order]
    for rank, record in enumerate(selected, 1):
        record["stage1_rank"] = rank
        record["stage1_ranking_method"] = method
    return selected


def build_rpc_budget(
    *,
    top_n: int,
    n_windows: int,
    resolve_log_chunks: int,
    stability_log_chunks_per_window: int,
    measured_calls: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    """Return separate measured and deliberately conservative RPC call books.

    Resolution upper bound assumes all three official Slipstream factories may
    return distinct pools (six factory lookups plus six identity/state calls per
    pool).  The eight preregistered cross routes are measured once per batch,
    not once per candidate: 11 reads each plus one fixed block read.
    """
    for name, value in {
        "top_n": top_n,
        "n_windows": n_windows,
        "resolve_log_chunks": resolve_log_chunks,
        "stability_log_chunks_per_window": stability_log_chunks_per_window,
    }.items():
        if isinstance(value, bool) or int(value) <= 0:
            raise ValueError(f"{name} must be positive")
    measured: dict[str, int] = {}
    for method, value in (measured_calls or {}).items():
        if isinstance(value, bool) or int(value) < 0:
            raise ValueError("measured RPC counts must be non-negative integers")
        measured[str(method)] = int(value)

    upper = {
        "batch_tip_calls": 2,  # resolve + stability tips
        "resolve_factory_lookup_calls": int(top_n) * 6,
        "resolve_candidate_validation_calls": int(top_n) * 18,
        "resolve_window_log_calls": int(top_n) * int(resolve_log_chunks),
        "stability_window_log_calls": (
            int(top_n) * int(n_windows) * int(stability_log_chunks_per_window)
        ),
        "terminal_live_state_calls": int(top_n) * 2,
        "cross_route_fixed_batch_calls": 8 * 11 + 1,
    }
    return {
        "top_n": int(top_n),
        "n_windows": int(n_windows),
        "measured_calls_by_method": measured,
        "measured_total_calls": sum(measured.values()),
        "upper_components": upper,
        "upper_total_calls": sum(upper.values()),
        "upper_bound_semantics": (
            "conservative request count before provider retry attempts; cross routes "
            "are one fixed-block batch snapshot, not top_n multiplied"
        ),
    }


__all__ = [
    "DEFAULT_PROXY_HORIZON_HOURS",
    "MIN_CORRELATION_PAIRS",
    "PROXY_VALID_SPEARMAN_MIN",
    "PRODUCTION_EVIDENCE",
    "build_rpc_budget",
    "correlate_proxy_with_netcover",
    "enrich_with_proxy",
    "proxy_netcover",
    "rank_stage1",
]
