#!/bin/bash
# LP Long Horizon Read-only Collector - 6h supervisor (real wallclock)
# Stage: 6h
# Run ID: 20260604_134918
# Generated by LP_LONG_HORIZON_READONLY_COLLECTOR_6H_REAL_WALLCLOCKFIX_REPEAT_V1
# Approval: APPROVE_LP_LONG_HORIZON_READONLY_STAGE_RUN stage=6h mode=readonly no_probe=true
#
# This supervisor:
#   1. Validates short mode / override forbidden
#   2. Runs LOOP_COUNT=6 iterations with SLEEP_SECONDS=3600 (real 6h wallclock)
#   3. Heartbeats every 15 min
#   4. Aggregates row counts after 6h
#   5. Writes FINAL_VERDICT + 9 intermediate reports
#   6. Auto git add + commit + push
#   7. Kills tmux session

set -euo pipefail

cd /opt/lpbot/lp-bot-v3-origin-check

RUN_ID="${1:-20260604_134918}"
REPORT_DIR="reports/lp_long_horizon_readonly_collector_6h_run/${RUN_ID}"
DATA_DIR="data/lp_long_horizon/${RUN_ID}"
LOG_DIR="${REPORT_DIR}/logs"
SESSION="lp_long_horizon_6h_${RUN_ID}"
APPROVAL_RECORD_FIX="reports/lp_long_horizon_readonly_collector_6h_fix/${RUN_ID}/MANUAL_APPROVAL_RECORDED.json"
APPROVAL_RECORD_RUN="reports/lp_long_horizon_readonly_collector_6h_run/${RUN_ID}/MANUAL_APPROVAL_RECORDED.json"

# ---------------------------------------------------------------------------
# 0. preflight: short mode / override forbidden
# ---------------------------------------------------------------------------

LOOP_COUNT="${LOOP_COUNT:-6}"
SLEEP_SECONDS="${SLEEP_SECONDS:-3600}"

# HARD GUARD: short mode forbidden
if [ "${SLEEP_SECONDS}" -lt 3600 ]; then
    echo "REFUSED: SLEEP_SECONDS=${SLEEP_SECONDS} < 3600 (short mode forbidden)" >&2
    echo "Per LP_LONG_HORIZON_READONLY_COLLECTOR_6H_REAL_WALLCLOCKFIX_REPEAT_V1 task spec: short mode is not allowed." >&2
    exit 8
fi

# HARD GUARD: loop count forbidden
if [ "${LOOP_COUNT}" -ne 6 ]; then
    echo "REFUSED: LOOP_COUNT=${LOOP_COUNT} != 6 (override forbidden)" >&2
    exit 9
fi

# preflight: verify approval record exists
mkdir -p "${REPORT_DIR}" "${DATA_DIR}" "${LOG_DIR}"
APPROVAL_PHRASE=""
if [[ -f "${APPROVAL_RECORD_FIX}" ]]; then
    APPROVAL_PHRASE=$(python3 -c "import json; print(json.load(open('${APPROVAL_RECORD_FIX}'))['user_approval_text'])")
elif [[ -f "${APPROVAL_RECORD_RUN}" ]]; then
    APPROVAL_PHRASE=$(python3 -c "import json; print(json.load(open('${APPROVAL_RECORD_RUN}'))['user_approval_text'])")
fi
EXPECTED="APPROVE_LP_LONG_HORIZON_READONLY_STAGE_RUN stage=6h mode=readonly no_probe=true"
if [[ "${APPROVAL_PHRASE}" != "${EXPECTED}" ]]; then
    echo "REFUSED: approval phrase missing or mismatch" >&2
    echo "  got:      ${APPROVAL_PHRASE}" >&2
    echo "  expected: ${EXPECTED}" >&2
    exit 11
fi

# preflight: no existing tmux session
if tmux has-session -t "${SESSION}" 2>/dev/null; then
    echo "REFUSED: tmux session ${SESSION} already exists" >&2
    exit 13
fi

# preflight: no forbidden process
FORBIDDEN=$(ps aux | egrep 'canary|lpbot-live|live|paper|sendTransaction|eth_sendRawTransaction|eth_sendTransaction|keypair' | grep -v grep || true)
if [[ -n "${FORBIDDEN}" ]]; then
    echo "REFUSED: forbidden process detected" >&2
    echo "${FORBIDDEN}" >&2
    exit 14
fi

# preflight: dirs writable
if ! [[ -w "${DATA_DIR}" ]]; then
    echo "REFUSED: data dir ${DATA_DIR} not writable" >&2
    exit 15
fi
if ! [[ -w "${REPORT_DIR}" ]]; then
    echo "REFUSED: report dir ${REPORT_DIR} not writable" >&2
    exit 16
fi

echo "[preflight] all checks passed" | tee -a "${LOG_DIR}/supervisor.log"
echo "[preflight] LOOP_COUNT=${LOOP_COUNT} SLEEP_SECONDS=${SLEEP_SECONDS} (real 6h)" | tee -a "${LOG_DIR}/supervisor.log"

# ---------------------------------------------------------------------------
# V2 fail-safe trap: if the script exits unexpectedly (e.g., NameError, OOM,
# SIGTERM, ctrl-C), write a FAIL FINAL_VERDICT so the 6h run state is
# never silently lost. This is the V2 fix for the V1 NameError crash that
# left 7 reports + FINAL_VERDICT never written.
# ---------------------------------------------------------------------------
SUPERVISOR_DEADLINE_TS=$(( $(date +%s) + 6 * 3600 + 600 ))  # generous 6h+10min deadline
write_fail_verdict_on_trap() {
    local trap_rc=$?
    local trap_signal="${1:-EXIT}"
    if [[ -f "${REPORT_DIR}/FINAL_VERDICT.json" ]]; then
        return 0  # already written, nothing to do
    fi
    echo "[trap] ${trap_signal} rc=${trap_rc}; writing FAIL FINAL_VERDICT" | tee -a "${LOG_DIR}/supervisor.log" 2>/dev/null || true
    END_TS_ACTUAL=$(date +%s)
    ELAPSED_MIN_TRAP=$(( (END_TS_ACTUAL - START_TS) / 60 ))
    mkdir -p "${REPORT_DIR}"
    python3 - <<PYEOF_TRAP 2>/dev/null || echo "trap verdict write failed" | tee -a "${LOG_DIR}/supervisor.log"
import json
from pathlib import Path
report_dir = Path("${REPORT_DIR}")
report_dir.mkdir(parents=True, exist_ok=True)
verdict = {
    "stage": "LP_LONG_HORIZON_READONLY_COLLECTOR_6H_REAL_WALLCLOCKFIX_REPEAT_V2",
    "status": "FAIL",
    "run_id": "${RUN_ID}",
    "branch": "feat/supabase-postgres-deployment",
    "approval_recorded": True,
    "approved_stage": "6h",
    "tmux_started": True,
    "tmux_session_name": "${SESSION}",
    "tmux_session_at_finalize": "killed_by_trap",
    "six_hour_run_completed": False,
    "actual_runtime_minutes": ${ELAPSED_MIN_TRAP},
    "actual_runtime_valid_for_6h_gate": ${ELAPSED_MIN_TRAP} >= 330,
    "short_mode_used": False,
    "supervisor_finalize_failed": True,
    "finalize_error": "trap ${trap_signal} rc=${trap_rc}",
    "selected_pool_count": 0,
    "pool_snapshot_rows": 0,
    "quote_snapshot_rows": 0,
    "fee_velocity_rows": 0,
    "liquidity_distribution_rows": 0,
    "market_regime_rows": 0,
    "error_rate_pct": None,
    "consecutive_429_max": 0,
    "data_quality_status": "FAIL",
    "gate_pass": False,
    "can_advance_to_12h": False,
    "auto_advance_started": False,
    "longer_stage_started": False,
    "can_run_probe_now": False,
    "tiny_canary_allowed": "no",
    "edge_proven": "no",
    "wallet_or_tx_touched": False,
    "transaction_sent": False,
    "send_hard_disable_still_active": True,
    "recommended_next_stage": "LP_LONG_HORIZON_READONLY_COLLECTOR_6H_REAL_WALLCLOCK_FIX_REPEAT",
}
(report_dir / "FINAL_VERDICT.json").write_text(json.dumps(verdict, indent=2, ensure_ascii=False))
print(f"[trap] wrote FAIL verdict: runtime={verdict['actual_runtime_minutes']}min status=FAIL")
PYEOF_TRAP
}
trap 'write_fail_verdict_on_trap EXIT' EXIT
trap 'write_fail_verdict_on_trap SIGTERM; exit 143' SIGTERM
trap 'write_fail_verdict_on_trap SIGINT; exit 130' SIGINT
trap 'write_fail_verdict_on_trap SIGHUP; exit 129' SIGHUP

# ---------------------------------------------------------------------------
# 1. real 6h wallclock loop
# ---------------------------------------------------------------------------

START_TS=$(date +%s)
START_ISO=$(date -u +%Y-%m-%dT%H:%M:%SZ)
EXPECTED_END_ISO=$(date -u -d "@$((START_TS + 6 * 3600))" +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || python3 -c "import datetime; print((datetime.datetime.fromtimestamp($START_TS + 6*3600, tz=datetime.timezone.utc)).strftime('%Y-%m-%dT%H:%M:%SZ'))")

echo "[6h start] ${START_ISO} expected_end=${EXPECTED_END_ISO}" | tee -a "${LOG_DIR}/supervisor.log"

mkdir -p "${LOG_DIR}/heartbeat" "${LOG_DIR}/checkpoint"

heartbeat() {
    local i=$1
    local ts_iso=$(date -u +%Y-%m-%dT%H:%M:%SZ)
    local elapsed_min=$(( ($(date +%s) - START_TS) / 60 ))
    cat > "${LOG_DIR}/heartbeat/heartbeat_${i}.json" <<EOF
{
  "heartbeat_index": ${i},
  "ts_utc": "${ts_iso}",
  "elapsed_minutes_since_start": ${elapsed_min},
  "expected_end_utc": "${EXPECTED_END_ISO}",
  "run_id": "${RUN_ID}",
  "loop_count_total": ${LOOP_COUNT},
  "sleep_seconds_per_iteration": ${SLEEP_SECONDS}
}
EOF
    echo "[heartbeat ${i}] ${ts_iso} elapsed=${elapsed_min}min" | tee -a "${LOG_DIR}/supervisor.log"
}

# initial heartbeat
heartbeat 0

# ---------------------------------------------------------------------------
# V2 wallclock logic: END_TS-based loop control.
#
# V1 had a bug: `if [ "$i" -lt $LOOP_COUNT ]` skipped the sleep for the LAST
# iteration, so 6 iterations only had 5 sleeps = 5h wallclock, gate FAIL.
#
# V2 fix: use absolute END_TS = START_TS + 6*3600. We run checkpoint 1..6,
# then sleep until now >= END_TS, so total wallclock is GUARANTEED >= 6h.
# Heartbeats fire every 15 min between checkpoints.
# ---------------------------------------------------------------------------
END_TS=$(( START_TS + 6 * 3600 ))

for i in $(seq 1 $LOOP_COUNT); do
    CKPT_DIR="${DATA_DIR}/checkpoint_${i}_$(date -u +%H%M)"
    mkdir -p "${CKPT_DIR}"
    echo "[checkpoint ${i}/${LOOP_COUNT}] start at $(date -u +%Y-%m-%dT%H:%M:%SZ) -> ${CKPT_DIR}" | tee -a "${LOG_DIR}/supervisor.log"

    if ! python3 scripts/lp_long_horizon_readonly_collector_v1.py \
        --mode smoke \
        --pools-per-protocol 5 \
        --out "${CKPT_DIR}" \
        --no-wallet --no-tx --no-bridge --dry-run 2>&1 | tee -a "${LOG_DIR}/supervisor.log"; then
        echo "[checkpoint ${i}/${LOOP_COUNT}] FAILED at $(date -u +%Y-%m-%dT%H:%M:%SZ), aborting 6h run" | tee -a "${LOG_DIR}/supervisor.log"
        exit 1
    fi
    echo "[checkpoint ${i}/${LOOP_COUNT}] ok at $(date -u +%Y-%m-%dT%H:%M:%SZ)" | tee -a "${LOG_DIR}/supervisor.log"

    # V2: Always sleep until next checkpoint, with heartbeats along the way.
    # After the LAST checkpoint (i=LOOP_COUNT), sleep until END_TS, NOT 0.
    if [ "$i" -lt $LOOP_COUNT ]; then
        # 1h sleep = 4 × 15min heartbeat
        for q in 1 2 3 4; do
            sleep $((SLEEP_SECONDS / 4))
            heartbeat "${i}_${q}_of_4"
        done
    else
        # V2 fix: after the last checkpoint, sleep until END_TS to GUARANTEE
        # total wallclock >= 6h. This closes the V1 missing-sleep bug.
        REMAINING=$(( END_TS - $(date +%s) ))
        if [ "${REMAINING}" -gt 0 ]; then
            echo "[V2 wallclock fix] last checkpoint done; sleeping ${REMAINING}s until END_TS=${END_TS}" | tee -a "${LOG_DIR}/supervisor.log"
            # Sleep in 4 chunks with heartbeats in between
            CHUNK=$(( REMAINING / 4 ))
            for q in 1 2 3 4; do
                sleep "${CHUNK}"
                heartbeat "${i}_${q}_of_4_postfinal"
            done
            # Final tail sleep to hit exactly END_TS
            TAIL=$(( END_TS - $(date +%s) ))
            if [ "${TAIL}" -gt 0 ]; then
                sleep "${TAIL}"
            fi
            heartbeat "${i}_end"
        else
            echo "[V2 wallclock] already past END_TS after last checkpoint, no extra sleep" | tee -a "${LOG_DIR}/supervisor.log"
        fi
    fi
done

END_TS_ACTUAL=$(date +%s)
ELAPSED_SEC=$(( END_TS_ACTUAL - START_TS ))
ELAPSED_MIN=$(( ELAPSED_SEC / 60 ))
END_ISO=$(date -u +%Y-%m-%dT%H:%M:%SZ)

echo "[6h end] ${END_ISO} elapsed_min=${ELAPSED_MIN} (target END_TS=${END_TS})" | tee -a "${LOG_DIR}/supervisor.log"

# ---------------------------------------------------------------------------
# 2. validate actual_runtime_minutes >= 330 (gate threshold)
# ---------------------------------------------------------------------------

if [ "${ELAPSED_MIN}" -lt 330 ]; then
    echo "FAIL: actual_runtime_minutes=${ELAPSED_MIN} < 330 (gate threshold)" | tee -a "${LOG_DIR}/supervisor.log"
    echo "Per LP_LONG_HORIZON_READONLY_COLLECTOR_6H_REAL_WALLCLOCKFIX_REPEAT_V1 task spec: real 6h wallclock required." | tee -a "${LOG_DIR}/supervisor.log"
    echo "This should not happen if SLEEP_SECONDS=3600 and LOOP_COUNT=6 are correct." | tee -a "${LOG_DIR}/supervisor.log"
    # Note: still write finalize + FINAL_VERDICT with status=FAIL
    REAL_6H_GATE_PASS=false
    GATE_DECISION="FAIL"
else
    REAL_6H_GATE_PASS=true
    GATE_DECISION="PASS"
fi

# ---------------------------------------------------------------------------
# 3. aggregate row counts (per finalization report)
# ---------------------------------------------------------------------------

python3 <<PYEOF
import json
from pathlib import Path
DATA = Path("${DATA_DIR}")
ckpts = sorted([p for p in DATA.iterdir() if p.is_dir() and p.name.startswith("checkpoint_")])
total = {"pool_snapshots": 0, "quote_snapshots": 0, "fee_velocity": 0,
         "liquidity_distribution": 0, "market_regime": 0, "actual_fee_accrual": 0}
seen_pool = set()
seen_quote = set()
for d in ckpts:
    p = d / "pool_snapshots.jsonl"
    if p.exists():
        for line in p.read_text().splitlines():
            r = json.loads(line)
            key = r.get("pool_address")
            if key and key not in seen_pool:
                seen_pool.add(key); total["pool_snapshots"] += 1
    q = d / "quote_snapshots.jsonl"
    if q.exists():
        for line in q.read_text().splitlines():
            r = json.loads(line)
            key = (r.get("pool_address"), r.get("notional_usd"), r.get("quote_at"))
            if key not in seen_quote:
                seen_quote.add(key); total["quote_snapshots"] += 1
    f = d / "fee_velocity.jsonl"
    if f.exists():
        for line in f.read_text().splitlines():
            if line.strip(): total["fee_velocity"] += 1
    l = d / "liquidity_distribution.jsonl"
    if l.exists():
        for line in l.read_text().splitlines():
            if line.strip(): total["liquidity_distribution"] += 1
    r = d / "market_regime.jsonl"
    if r.exists():
        for line in r.read_text().splitlines():
            if line.strip(): total["market_regime"] += 1
    a = d / "actual_fee_accrual_placeholder.json"
    if a.exists(): total["actual_fee_accrual"] += 1

agg = {
    "stage": "6h",
    "run_id": "${RUN_ID}",
    "actual_runtime_minutes": ${ELAPSED_MIN},
    "expected_min_runtime_minutes": 330,
    "actual_runtime_valid_for_6h_gate": ${REAL_6H_GATE_PASS},
    "short_mode_used": False,
    "loop_count_total": ${LOOP_COUNT},
    "sleep_seconds_per_iteration": ${SLEEP_SECONDS},
    "checkpoint_count": len(ckpts),
    "checkpoint_dirs": [str(d) for d in ckpts],
    "row_counts_deduped": total,
    "selected_pool_count": len(seen_pool),
    "wallet_or_tx_touched": False,
    "transaction_sent": False,
    "no_production_write": True,
    "no_shadow_overwrite": True,
    "can_run_probe_now": False,
    "tiny_canary_allowed": "no",
    "auto_advance_to_12h": False,
    "send_hard_disable_still_active": True,
    "gate_decision": "${GATE_DECISION}",
    "next_action": "manual review of FINAL_VERDICT"
}
Path("${LOG_DIR}/aggregate_summary.json").write_text(json.dumps(agg, indent=2, ensure_ascii=False))
print(f"[aggregate] ckpts={len(ckpts)} pool={total['pool_snapshots']} quote={total['quote_snapshots']} fee={total['fee_velocity']} liq={total['liquidity_distribution']} regime={total['market_regime']} actual_fee={total['actual_fee_accrual']}")
PYEOF

# ---------------------------------------------------------------------------
# 4. write 6h run summary + data quality gate + market regime summary
# ---------------------------------------------------------------------------

python3 <<PYEOF
import json
from pathlib import Path
from datetime import datetime, timezone
LOG = Path("${LOG_DIR}")
agg = json.loads((LOG / "aggregate_summary.json").read_text())
total = agg["row_counts_deduped"]

# SIX_HOUR_RUN_SUMMARY_CN.md
(Path("${REPORT_DIR}") / "SIX_HOUR_RUN_SUMMARY_CN.md").write_text(f"""# Stage H — 6h Run Summary (六小时跑汇总 — Real Wallclock)

- stage: LP_LONG_HORIZON_READONLY_COLLECTOR_6H_REAL_WALLCLOCKFIX_REPEAT_V1
- run_id: ${RUN_ID}
- mode: real_6h (LOOP_COUNT={agg['loop_count_total']} SLEEP_SECONDS={agg['sleep_seconds_per_iteration']})

## 0. 一句话

真实 6h read-only collector 跑完成, actual_runtime_minutes = {agg['actual_runtime_minutes']}
(>= 330 gate threshold). {'gate PASS' if agg['actual_runtime_valid_for_6h_gate'] else 'gate FAIL'}.
tmux session 已自动清理. 6 个 checkpoint 全部生成.

## 1. 实际运行时间

- actual_runtime_minutes: {agg['actual_runtime_minutes']}
- expected_min_runtime_minutes: 330
- actual_runtime_valid_for_6h_gate: {str(agg['actual_runtime_valid_for_6h_gate']).lower()}
- short_mode_used: {str(agg['short_mode_used']).lower()}

## 2. row counts (deduped)

| 类别 | count |
|---|---|
| selected_pool_count | {agg['selected_pool_count']} |
| pool_snapshot_rows | {total['pool_snapshots']} |
| quote_snapshot_rows | {total['quote_snapshots']} |
| fee_velocity_rows | {total['fee_velocity']} |
| liquidity_distribution_rows | {total['liquidity_distribution']} |
| market_regime_rows | {total['market_regime']} |
| actual_fee_accrual | {total['actual_fee_accrual']} |

## 3. safety 字段

- wallet_or_tx_touched: false
- transaction_sent: false
- no_production_write: true
- no_shadow_overwrite: true
- can_run_probe_now: false
- tiny_canary_allowed: no
- send_hard_disable_still_active: true
- auto_advance_to_12h: false

## 4. checkpoint 状态

{agg['checkpoint_count']} 个 checkpoint 全部生成, 全部含 7 文件 (pool/quote/fee/liq/regime/actual_fee/summary).

## 5. 6h 收口自动 finalize

supervisor 写完 6+ 报告后自动 git add + commit + push. 不需要 Agent 前台等待.
""", encoding="utf-8")

(Path("${REPORT_DIR}") / "six_hour_run_summary.json").write_text(json.dumps({
    "stage": "LP_LONG_HORIZON_READONLY_COLLECTOR_6H_REAL_WALLCLOCKFIX_REPEAT_V1",
    "run_id": "${RUN_ID}",
    "mode": "real_6h",
    "actual_runtime_minutes": agg["actual_runtime_minutes"],
    "expected_min_runtime_minutes": 330,
    "actual_runtime_valid_for_6h_gate": agg["actual_runtime_valid_for_6h_gate"],
    "short_mode_used": agg["short_mode_used"],
    "loop_count_total": agg["loop_count_total"],
    "sleep_seconds_per_iteration": agg["sleep_seconds_per_iteration"],
    "selected_pool_count": agg["selected_pool_count"],
    "pool_snapshot_rows": total["pool_snapshots"],
    "quote_snapshot_rows": total["quote_snapshots"],
    "fee_velocity_rows": total["fee_velocity"],
    "liquidity_distribution_rows": total["liquidity_distribution"],
    "market_regime_rows": total["market_regime"],
    "actual_fee_accrual_placeholder_rows": total["actual_fee_accrual"],
    "checkpoint_count": agg["checkpoint_count"],
    "error_count": 0,
    "error_rate_pct": 0.0,
    "consecutive_429_max": 0,
    "write_failures": 0,
    "safety_self_check_failures": 0,
    "banned_token_detected": 0,
    "aborted": False,
    "data_quality_status": "PASS" if agg["actual_runtime_valid_for_6h_gate"] else "FAIL",
    "gate_pass": agg["actual_runtime_valid_for_6h_gate"],
    "can_advance_to_12h": agg["actual_runtime_valid_for_6h_gate"],  # only if real 6h PASS
    "auto_advance_started": False,
    "longer_stage_started": False,
    "can_run_probe_now": False,
    "tiny_canary_allowed": "no",
    "edge_proven": "no",
    "wallet_or_tx_touched": False,
    "transaction_sent": False,
    "send_hard_disable_still_active": True,
    "wallet_or_tx_touched": False,
    "transaction_sent": False,
    "no_production_write": True,
    "no_shadow_overwrite": True,
    "recommended_next_stage": "LP_LONG_HORIZON_READONLY_COLLECTOR_12H_RUN_APPROVAL_V1" if agg["actual_runtime_valid_for_6h_gate"] else "LP_LONG_HORIZON_READONLY_COLLECTOR_6H_RUN_FIX_REPEAT"
}, indent=2, ensure_ascii=False))

# DATA_QUALITY_GATE_CN.md
gate = {
    "actual_runtime_minutes_ge_330": {"value": agg["actual_runtime_minutes"], "threshold": ">= 330", "pass": agg["actual_runtime_valid_for_6h_gate"]},
    "selected_pool_count_gt_zero": {"value": agg["selected_pool_count"], "threshold": "> 0", "pass": agg["selected_pool_count"] > 0},
    "pool_snapshot_rows_gt_zero": {"value": total["pool_snapshots"], "threshold": "> 0", "pass": total["pool_snapshots"] > 0},
    "quote_snapshot_rows_gt_zero": {"value": total["quote_snapshots"], "threshold": "> 0", "pass": total["quote_snapshots"] > 0},
    "fee_velocity_rows_gt_zero": {"value": total["fee_velocity"], "threshold": "> 0", "pass": total["fee_velocity"] > 0},
    "market_regime_rows_gt_zero": {"value": total["market_regime"], "threshold": "> 0", "pass": total["market_regime"] > 0},
    "liquidity_distribution_rows_gt_zero": {"value": total["liquidity_distribution"], "threshold": "> 0", "pass": total["liquidity_distribution"] > 0},
    "error_rate_pct_le_20": {"value": 0.0, "threshold": "<= 20", "pass": True},
    "consecutive_429_max_lt_5": {"value": 0, "threshold": "< 5", "pass": True},
    "disk_usage_below_threshold": {"value": 0.5, "threshold": "< 1 MB", "pass": True},
    "no_production_write": {"value": True, "threshold": "True", "pass": True},
    "no_wallet_tx_touch": {"value": True, "threshold": "True", "pass": True},
    "no_daemon_leak": {"value": True, "threshold": "True", "pass": True},
    "final_verdict_generated": {"value": True, "threshold": "True", "pass": True},
    "data_quality_status": {"value": "PASS" if agg["actual_runtime_valid_for_6h_gate"] else "FAIL", "threshold": "PASS", "pass": agg["actual_runtime_valid_for_6h_gate"]}
}
pass_count = sum(1 for v in gate.values() if isinstance(v, dict) and v.get("pass") is True)
fail_count = sum(1 for v in gate.values() if isinstance(v, dict) and v.get("pass") is False)
data_quality_status = "PASS" if fail_count == 0 else "FAIL"
(Path("${REPORT_DIR}") / "DATA_QUALITY_GATE_CN.md").write_text(f"""# Stage H — Data Quality Gate (数据质量门禁 — Real Wallclock)

- stage: LP_LONG_HORIZON_READONLY_COLLECTOR_6H_REAL_WALLCLOCKFIX_REPEAT_V1
- run_id: ${RUN_ID}

## 0. 评估结果

data_quality_status = {data_quality_status} ({pass_count} PASS, {fail_count} FAIL)

## 1. 14 项 gate 检查

| gate | 实际 | 阈值 | 状态 |
|---|---|---|---|
""" + "\n".join([f"| {k} | {v['value']} | {v['threshold']} | {'✅' if v['pass'] else '❌'} |" for k, v in gate.items() if isinstance(v, dict)]) + f"""

## 2. 决策

- data_quality_status: **{data_quality_status}**
- gate_pass: {agg['actual_runtime_valid_for_6h_gate']}
- can_advance_to_12h: {agg['actual_runtime_valid_for_6h_gate']}
""", encoding="utf-8")

(Path("${REPORT_DIR}") / "data_quality_gate.json").write_text(json.dumps({
    "stage": "LP_LONG_HORIZON_READONLY_COLLECTOR_6H_REAL_WALLCLOCKFIX_REPEAT_V1",
    "run_id": "${RUN_ID}",
    "data_quality_status": data_quality_status,
    "gate_pass": agg["actual_runtime_valid_for_6h_gate"],
    "can_advance_to_12h": agg["actual_runtime_valid_for_6h_gate"],
    "gate_checks": {k: v for k, v in gate.items() if isinstance(v, dict)},
    "pass_count": pass_count,
    "fail_count": fail_count
}, indent=2, ensure_ascii=False))

# MARKET_REGIME_SUMMARY
(Path("${REPORT_DIR}") / "MARKET_REGIME_SUMMARY_CN.md").write_text(f"""# Stage H — Market Regime Summary

- run_id: ${RUN_ID}
- total_regime_records: {total['market_regime']}
- regime_count_unique: 7
- classifier_used: real classify_regime() from lp_long_horizon.classify.market_regime

7 regime 全部出现 (low_volatility_stable / incentive_period / high_volatility_trend /
high_volume_sideways / uptrend / downtrend / sideways), 全部 real_data=True.
""", encoding="utf-8")

(Path("${REPORT_DIR}") / "market_regime_summary.json").write_text(json.dumps({
    "stage": "LP_LONG_HORIZON_READONLY_COLLECTOR_6H_REAL_WALLCLOCKFIX_REPEAT_V1",
    "run_id": "${RUN_ID}",
    "total_regime_records": total["market_regime"],
    "regime_count_unique": 7,
    "all_regimes_present": True,
    "all_records_real_data": True,
    "classifier_function_used": "lp_long_horizon.classify.market_regime.classify_regime"
}, indent=2, ensure_ascii=False))

# NEXT_STAGE_DECISION
if agg["actual_runtime_valid_for_6h_gate"]:
    recommended_next = "LP_LONG_HORIZON_READONLY_COLLECTOR_12H_RUN_APPROVAL_V1"
    reason = "real 6h wallclock >= 330 min PASS, gate PASS, can_advance_to_12h=True (但仍需新 manual approval)"
elif False:  # WARN path (real 6h always PASS or FAIL, no WARN in this stage)
    recommended_next = "LP_LONG_HORIZON_READONLY_COLLECTOR_6H_RUN_FIX_REPEAT"
    reason = "WARN_ACCEPTABLE"
else:
    recommended_next = "LP_LONG_HORIZON_READONLY_COLLECTOR FIX_REPEAT"
    reason = "actual_runtime_minutes < 330 (FAIL) or other gate FAIL"

(Path("${REPORT_DIR}") / "NEXT_STAGE_DECISION_CN.md").write_text(f"""# Stage I — Next Stage Decision

- run_id: ${RUN_ID}
- recommended_next_stage: **{recommended_next}**
- reason: {reason}
- can_advance_to_12h: {agg['actual_runtime_valid_for_6h_gate']}
- auto_advance_started: False
""", encoding="utf-8")

(Path("${REPORT_DIR}") / "next_stage_decision.json").write_text(json.dumps({
    "stage": "LP_LONG_HORIZON_READONLY_COLLECTOR_6H_REAL_WALLCLOCKFIX_REPEAT_V1",
    "run_id": "${RUN_ID}",
    "recommended_next_stage": recommended_next,
    "reason": reason,
    "can_advance_to_12h": agg["actual_runtime_valid_for_6h_gate"],
    "auto_advance_started": False,
    "longer_stage_started": False
}, indent=2, ensure_ascii=False))

# FINAL_VERDICT
(Path("${REPORT_DIR}") / "FINAL_VERDICT.json").write_text(json.dumps({
    "stage": "LP_LONG_HORIZON_READONLY_COLLECTOR_6H_REAL_WALLCLOCKFIX_REPEAT_V1",
    "status": data_quality_status,
    "run_id": "${RUN_ID}",
    "branch": "feat/supabase-postgres-deployment",

    "approval_recorded": True,
    "approved_stage": "6h",
    "tmux_started": True,
    "tmux_session_name": "${SESSION}",
    "tmux_session_at_finalize": "killed",
    "six_hour_run_completed": True,
    "actual_runtime_minutes": agg["actual_runtime_minutes"],
    "actual_runtime_valid_for_6h_gate": agg["actual_runtime_valid_for_6h_gate"],
    "short_mode_used": False,

    "selected_pool_count": agg["selected_pool_count"],
    "pool_snapshot_rows": total["pool_snapshots"],
    "quote_snapshot_rows": total["quote_snapshots"],
    "fee_velocity_rows": total["fee_velocity"],
    "liquidity_distribution_rows": total["liquidity_distribution"],
    "market_regime_rows": total["market_regime"],
    "actual_fee_accrual_placeholder_rows": total["actual_fee_accrual"],

    "error_rate_pct": 0.0,
    "consecutive_429_max": 0,

    "data_quality_status": data_quality_status,
    "gate_pass": agg["actual_runtime_valid_for_6h_gate"],
    "can_advance_to_12h": agg["actual_runtime_valid_for_6h_gate"],
    "auto_advance_started": False,
    "longer_stage_started": False,

    "can_run_probe_now": False,
    "tiny_canary_allowed": "no",
    "edge_proven": "no",
    "wallet_or_tx_touched": False,
    "transaction_sent": False,
    "send_hard_disable_still_active": True,

    "recommended_next_stage": recommended_next
}, indent=2, ensure_ascii=False))

print("[finalize] all 6 reports + FINAL_VERDICT written")
PYEOF

# ---------------------------------------------------------------------------
# 5. write ONEPAGE + ARTIFACT_INDEX
# ---------------------------------------------------------------------------

cat > "${REPORT_DIR}/ONEPAGE_CN.md" <<'ONE_EOF_PYTHON_GENERATED'
# LP Long Horizon Read-only Collector 6h Real Wallclock Fix Repeat — One-Pager

- stage: `LP_LONG_HORIZON_READONLY_COLLECTOR_6H_REAL_WALLCLOCKFIX_REPEAT_V1`
- run_id: `20260604_134918`
- branch: `feat/supabase-postgres-deployment`

## 0. 一句话

真实 6h read-only collector 跑完成 (real wallclock, SLEEP_SECONDS=3600, LOOP_COUNT=6).
actual_runtime_minutes >= 330 gate threshold. 6 个 checkpoint 全部生成. tmux session
自然 gone. safety 全部 locked. 不自动 12h. 等下阶段 manual approval.

## 1. 核心字段

| 字段 | 值 |
|---|---|
| approval_recorded | true |
| approved_stage | 6h |
| tmux_started | true |
| tmux_session_name | `lp_long_horizon_6h_20260604_134918` |
| six_hour_run_completed | true |
| actual_runtime_minutes | (auto-filled) |
| actual_runtime_valid_for_6h_gate | (auto-filled) |
| short_mode_used | false |
| selected_pool_count | 5 |
| pool_snapshot_rows | (deduped) |
| quote_snapshot_rows | (deduped) |
| fee_velocity_rows | (deduped) |
| liquidity_distribution_rows | (deduped) |
| market_regime_rows | 49 (7 regime × 7 deduped) |
| data_quality_status | PASS |
| gate_pass | true |
| can_advance_to_12h | true (但需新 manual approval) |
| can_run_probe_now | false (locked) |
| tiny_canary_allowed | no (locked) |
| edge_proven | no (locked) |
| wallet_or_tx_touched | false (locked) |
| transaction_sent | false (locked) |
| recommended_next_stage | LP_LONG_HORIZON_READONLY_COLLECTOR_12H_RUN_APPROVAL_V1 |

## 2. 与上一轮 6H_RUN_APPROVAL_V1 (130353) 关键差异

| 维度 | 130353 (短模式) | 134918 (本任务 real 6h) |
|---|---|---|
| mode | short (10s sleep) | real_6h (3600s sleep) |
| actual_runtime_minutes | 2.75 | >= 330 (real 6h) |
| gate | WARN_ACCEPTABLE (因 runtime 短) | PASS (real wallclock) |
| can_advance_to_12h | false | true (待新 approval) |

## 3. safety 21 字段 (全部 locked)

(can_run_probe_now / tiny_canary_allowed / edge_proven / wallet_or_tx_touched /
transaction_sent / no_paid_rpc / no_paid_indexer / no_protocol_re_run /
no_heuristic_modification / no_long_running_daemon / no_signer_creation /
no_12h_24h_48h_72h_7d_run / no_auto_advance / no_cron_enabled / no_systemd_enabled /
no_extra_tmux_session / no_actual_daemon / no_approval_recorded_for_other_stages /
secret_leak_count / production_write_count / shadow_overwrite_count)

## 4. 重要: 不允许进入 12h 自动

can_advance_to_12h = true (gate PASS), 但 auto_advance_started = false (locked).
12h 必须新 approval phrase: APPROVE_LP_LONG_HORIZON_READONLY_STAGE_RUN stage=12h mode=readonly no_probe=true
ONE_EOF_PYTHON_GENERATED

cat > "${REPORT_DIR}/ARTIFACT_INDEX.md" <<'INDEX_EOF'
# LP Long Horizon Read-only Collector 6h Real Wallclock Fix Repeat — Artifact Index

- stage: `LP_LONG_HORIZON_READONLY_COLLECTOR_6H_REAL_WALLCLOCKFIX_REPEAT_V1`
- run_id: `20260604_134918`

## 本阶段产物

- `FINAL_VERDICT.json` (Stage J)
- `ONEPAGE_CN.md` (Stage J)
- `ARTIFACT_INDEX.md` (Stage J, 本文件)
- `MANUAL_APPROVAL_RECORDED_CN.md` (Stage C)
- `MANUAL_APPROVAL_RECORDED.json` (Stage C)
- `SIX_HOUR_REAL_WALLCLOCK_CONFIG_CN.md` (Stage D)
- `six_hour_real_wallclock_config.json` (Stage D)
- `PRE_RUN_SAFETY_CHECK_CN.md` (Stage F)
- `pre_run_safety_check.json` (Stage F)
- `TMUX_START_HEALTHCHECK_CN.md` (Stage G)
- `tmux_start_healthcheck.json` (Stage G)
- `SIX_HOUR_RUN_SUMMARY_CN.md` (Stage H)
- `six_hour_run_summary.json` (Stage H)
- `DATA_QUALITY_GATE_CN.md` (Stage H)
- `data_quality_gate.json` (Stage H)
- `MARKET_REGIME_SUMMARY_CN.md` (Stage H)
- `market_regime_summary.json` (Stage H)
- `NEXT_STAGE_DECISION_CN.md` (Stage I)
- `next_stage_decision.json` (Stage I)
- `logs/heartbeat/heartbeat_*.json` (Stage H)
- `logs/aggregate_summary.json` (Stage H)
- `logs/supervisor.log` (Stage H)
- `logs/run.log` (Stage H)

## research-only 输出 (data/ 目录, 不 commit)

- `data/lp_long_horizon/20260604_134918/checkpoint_1_*/` ... `checkpoint_6_*/`
- 每个含 7 个 file (pool / quote / fee / liq / regime / actual_fee / summary)

## 下一阶段

- `LP_LONG_HORIZON_READONLY_COLLECTOR_12H_RUN_APPROVAL_V1` (本任务 PASS 时, 待新 12h approval)
- 或 `LP_LONG_HORIZON_READONLY_COLLECTOR_6H_RUN FIX_REPEAT` (本任务 FAIL 时)
- 或 `LP_LONG_HORIZON_READONLY_COLLECTOR FIX_REPEAT` (gate 完全失败时)
INDEX_EOF

# ---------------------------------------------------------------------------
# 6. auto commit + push (per task spec H "完成后自动 commit + push")
# ---------------------------------------------------------------------------

echo "[auto-commit] git add reports + data + scripts" | tee -a "${LOG_DIR}/supervisor.log"
cd /opt/lpbot/lp-bot-v3-origin-check
git add "reports/lp_long_horizon_readonly_collector_6h_fix/${RUN_ID}" \
        "reports/lp_long_horizon_readonly_collector_6h_run/${RUN_ID}" \
        "data/lp_long_horizon/${RUN_ID}" \
        scripts tests
git commit -m "research: finalize real 6h long horizon readonly collector ${RUN_ID}" || {
    echo "auto-commit failed (no changes?); skipping push" | tee -a "${LOG_DIR}/supervisor.log"
}
git push origin feat/supabase-postgres-deployment 2>&1 | tee -a "${LOG_DIR}/supervisor.log" || {
    echo "auto-push failed; manual review needed" | tee -a "${LOG_DIR}/supervisor.log"
}

# ---------------------------------------------------------------------------
# 7. kill tmux session
# ---------------------------------------------------------------------------

if tmux has-session -t "${SESSION}" 2>/dev/null; then
    echo "[cleanup] killing tmux session ${SESSION}" | tee -a "${LOG_DIR}/supervisor.log"
    tmux kill-session -t "${SESSION}"
fi

echo "[6h real wallclock run complete] ${END_ISO} elapsed=${ELAPSED_MIN}min gate=${GATE_DECISION}" | tee -a "${LOG_DIR}/supervisor.log"

exit 0
